<a href="https://colab.research.google.com/github/idkisma3l/ExamenPracticoFinal_ISI/blob/main/Proyecto_Examen_Final_ISID223_Google_Colab_Estilo_Dark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen Final Práctico - ISID223
Proyecto para Google Colab

In [ ]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from google.colab import files

## Cargar archivo CSV

In [6]:
# Cargar la base de datos
df = pd.read_csv("real_estate_ecuador_200k.csv")

# Mostrar las primeras filas
df.head()

,Titulo,Precio,Provincia,Lugar,Num. dormitorios,Num. banos,Area,Num. garages
0,Rento Suite 75 metros sector Republica del Sal...,395.66,Pichincha,"Pichincha, Av. Portugal & Av República de El S...",1.0,2.0,65,1.0
1,“Rento departamento en sector la Carolina”,773.69,Pichincha,"Pichincha, Catalina de Aldaz & Av. Portugal, Q...",2.0,2.0,88,1.0
2,Se Renta Amplio Departamento en el Sector de l...,616.94,Pichincha,"Pichincha, Marcos Jofre, Quito, Ecuador",4.0,4.0,214,1.0
3,Hermoso departamento de arriendo de oportunida...,286.69,Pichincha,"Pichincha, De la Prensa Y del Maestro, Quito, ...",2.0,2.0,98,1.0
4,"EN RENTA DEPARTAMENTO, CONJUNTO DIVINO NIÑO",131.54,Pichincha,"Pichincha, Turubamaba, Ecuador",3.0,2.0,53,NaN

## Perspectiva Financiera

In [27]:
# ================================
# PERSPECTIVA FINANCIERA
# ================================

# i. Precio Promedio de Alquiler (General y por Ciudad)

precio_promedio = df["Precio"].mean()

precio_ciudad = (
    df.groupby("Lugar")["Precio"]
      .mean()
      .reset_index()
      .rename(columns={
          "Lugar": "Ciudad",
          "Precio": "Precio Promedio"
      })
      .sort_values(by="Precio Promedio", ascending=False)
)

print("i. Precio Promedio General de Alquiler")
display(pd.DataFrame({
    "Indicador": ["Precio Promedio General"],
    "Valor": [round(precio_promedio, 2)]
}))

print("Precio Promedio por Ciudad")
display(precio_ciudad)


# ============================================
# ii. Costo Promedio por Metro Cuadrado
# ============================================

df["Costo_m2"] = df["Precio"] / df["Area"]

costo_m2 = df["Costo_m2"].mean()

print("ii. Costo Promedio por Metro Cuadrado")
display(pd.DataFrame({
    "Indicador": ["Costo Promedio por m²"],
    "Valor": [round(costo_m2, 2)]
}))


# ============================================
# iii. Rango de Precios por Provincia
# ============================================

rango_provincia = (
    df.groupby("Provincia")["Precio"]
      .agg(
          Precio_Minimo="min",
          Precio_Maximo="max",
          Precio_Promedio="mean"
      )
      .reset_index()
)

print("iii. Rango de Precios (Mínimo, Máximo y Promedio) por Provincia")
display(rango_provincia)

i. Precio Promedio General de Alquiler

                 Indicador   Valor
0  Precio Promedio General  732.35

Precio Promedio por Ciudad

                                              Ciudad  Precio Promedio
99   Pichincha, Avenida 10 de Agosto, Quito, Ecuador      9023.844069
38                            Manabí, Manta, Ecuador      6503.102091
215            Pichincha, La Delicia, Quito, Ecuador      4999.131409
189               Pichincha, Guamaní, Quito, Ecuador      3887.606034
0             Cotopaxi, Latacunga, Cotopaxi, Ecuador      3697.685799
..                                               ...              ...
293                   Pichincha, Turubamaba, Ecuador       120.211236
1                       Cotopaxi, Latacunga, Ecuador       118.854358
145     Pichincha, Comité del Pueblo, Quito, Ecuador       115.599590
249          Pichincha, Nueva Aurora, Quito, Ecuador        99.472081
304                    Santa Elena, Chanduy, Ecuador         8.968586

[305 rows x 2 columns]

ii. Costo Promedio por Metro Cuadrado

               Indicador  Valor
0  Costo Promedio por m²   5.89

iii. Rango de Precios (Mínimo, Máximo y Promedio) por Provincia

     Provincia  Precio_Minimo  Precio_Maximo  Precio_Promedio
0     Cotopaxi          94.47        4557.66      1814.528859
1       El Oro          98.42         155.03       124.352068
2   Esmeraldas         111.33         620.53       327.772537
3       Guayas         130.85        2816.34       614.669888
4     Imbabura         380.54         589.42       480.809447
5     Los Rios         176.04         295.08       233.589620
6       Manabí        5176.48        7920.44      6503.102091
7     Orellana         118.86         185.84       149.863608
8    Pichincha          80.21       11062.33       734.507750
9  Santa Elena           7.22          11.03         8.968586

## Perspectiva Producto

In [8]:
def tipo_propiedad(texto):
    texto = str(texto).lower()
    if "suite" in texto:
        return "Suite"
    elif "departamento" in texto:
        return "Departamento"
    elif "casa" in texto:
        return "Casa"
    elif "local" in texto:
        return "Local Comercial"
    elif "oficina" in texto:
        return "Oficina"
    elif "terreno" in texto:
        return "Terreno"
    else:
        return "Otro"

df["Tipo"] = df["Titulo"].apply(tipo_propiedad)

conteo_tipo = df["Tipo"].value_counts()
tamano_promedio = df.groupby("Provincia")["Area"].mean()

precio_habitaciones = df.groupby("Num. dormitorios")["Precio"].mean().sort_index()
premium = precio_habitaciones.diff()

display(conteo_tipo)
display(tamano_promedio)
display(premium)

Tipo
Departamento       85196
Suite              25868
Otro               23134
Oficina            23124
Local Comercial    21301
Casa               20174
Terreno             1203
Name: count, dtype: int64

Provincia
Cotopaxi           72.428405
El Oro           5947.770492
Esmeraldas        110.380597
Guayas            103.337822
Imbabura          140.623116
Los Rios           88.953416
Manabí            199.649038
Orellana           27.992736
Pichincha         166.801846
Santa Elena    199727.401515
Name: Area, dtype: float64

Num. dormitorios
1.0             NaN
2.0      -87.148764
3.0       95.253816
4.0      481.334452
5.0      234.446957
6.0      199.206322
7.0     1228.419473
8.0    -1888.112427
9.0     -443.386277
10.0    -279.339615
11.0      13.878501
Name: Precio, dtype: float64

## Perspectiva Geográfica

In [9]:
top5 = df.groupby("Lugar")["Precio"].mean().sort_values(ascending=False).head(5)
oferta = df["Provincia"].value_counts()

display(top5)
display(oferta)

Lugar
Pichincha, Avenida 10 de Agosto, Quito, Ecuador    9023.844069
Manabí, Manta, Ecuador                             6503.102091
Pichincha, La Delicia, Quito, Ecuador              4999.131409
Pichincha, Guamaní, Quito, Ecuador                 3887.606034
Cotopaxi, Latacunga, Cotopaxi, Ecuador             3697.685799
Name: Precio, dtype: float64

Provincia
Pichincha      180673
Guayas          13960
Los Rios         1288
Cotopaxi          859
Esmeraldas        804
El Oro            793
Manabí            416
Orellana          413
Imbabura          398
Santa Elena       396
Name: count, dtype: int64

## Segmentación del Mercado

In [10]:
Q1 = df["Precio"].quantile(0.25)
Q3 = df["Precio"].quantile(0.75)

def segmento(precio):
    if precio < Q1:
        return "Económico"
    elif precio > Q3:
        return "Lujo"
    else:
        return "Medio"

df["Tipo de Inmueble"] = df["Precio"].apply(segmento)
display(df["Tipo de Inmueble"].value_counts())

Tipo de Inmueble
Medio        100001
Lujo          50000
Económico     49999
Name: count, dtype: int64

# Total de propiedades

In [24]:
# KPI 3.0
fig3 = go.Figure(go.Indicator(
    mode="number",
    value=len(df),
    title={"text":"<b>Total de Propiedades</b>"},
    number={"font":{"size":50,"color":"#FFD54F"}}
))

fig3.update_layout(
    template=template_dark,
    paper_bgcolor="#111111",
    height=220
)

fig3.show()

## Dashboard

In [11]:

# ==========================
# ESTILO OSCURO PARA KPIs
# ==========================

template_dark = "plotly_dark"

# KPI 1
fig1 = go.Figure(go.Indicator(
    mode="number",
    value=precio_promedio,
    title={"text":"<b>Precio Promedio</b>"},
    number={"prefix":"$","font":{"size":46,"color":"#00E5FF"}}
))
fig1.update_layout(template=template_dark,paper_bgcolor="#111111",height=220)
fig1.show()

In [12]:
# KPI 2
fig2 = go.Figure(go.Indicator(
    mode="number",
    value=costo_m2,
    title={"text":"<b>Costo Promedio por m²</b>"},
    number={"prefix":"$","font":{"size":46,"color":"#00FF95"}}
))
fig2.update_layout(template=template_dark,paper_bgcolor="#111111",height=220)
fig2.show()

In [23]:
# KPI: Precio promedio por provincia

precio_provincia = df.groupby("Provincia")["Precio"].mean().sort_values(ascending=False)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=precio_provincia.index,
    y=precio_provincia.values,
    marker=dict(
        color=precio_provincia.values,
        colorscale="Turbo",
        line=dict(color="white", width=0.5)
    )
))

fig.update_layout(
    title="Precio Promedio por Provincia",
    template="plotly_dark",
    paper_bgcolor="#111111",
    plot_bgcolor="#111111",
    font=dict(color="white"),
    xaxis_title="Provincia",
    yaxis_title="Precio Promedio",
    height=600,
    width=1100
)

fig.show()

Promedio por ciudad

In [25]:
# KPI 3.1 - Precio Promedio por Ciudad

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=precio_ciudad.index,
        y=precio_ciudad.values,
        marker=dict(
            color=precio_ciudad.values,
            colorscale="Turbo",
            line=dict(color="white", width=0.5)
        )
    )
)

fig.update_layout(
    template="plotly_dark",
    paper_bgcolor="#111111",
    plot_bgcolor="#111111",
    font=dict(color="white"),
    title="Precio Promedio por Ciudad",
    xaxis_title="Ciudad",
    yaxis_title="Precio Promedio",
    height=600,
    width=1000
)

fig.show()

## Relación AREA VS PRECIO

In [26]:
# KPI 3.2 - Relación Área vs Precio

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["Area"],
        y=df["Precio"],
        mode="markers",
        marker=dict(
            size=7,
            color=df["Precio"],
            colorscale="Viridis",
            showscale=True
        )
    )
)

fig.update_layout(
    template="plotly_dark",
    paper_bgcolor="#111111",
    plot_bgcolor="#111111",
    font=dict(color="white"),
    title="Relación Área vs Precio",
    xaxis_title="Área (m²)",
    yaxis_title="Precio",
    height=600,
    width=1000
)

fig.show()

# Distribución por propiedades / Premium por habitación

In [20]:
fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type":"pie"},{"type":"bar"}]],
    subplot_titles=[
        "Tipo de Propiedad",
        "Premium por Habitación"
    ]
)

fig.add_trace(
    go.Pie(
        labels=conteo_tipo.index,
        values=conteo_tipo.values,
        hole=0.45,
        marker=dict(colors=[
            "#00E5FF",
            "#00FF95",
            "#FFD54F",
            "#FF6B6B",
            "#B388FF",
            "#FF9800",
            "#90CAF9"
        ])
    ),
    row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=premium.index.astype(str),
        y=premium.values,
        marker=dict(
            color=premium.values,
            colorscale="Plasma"
        )
    ),
    row=1, col=2
)

fig.update_layout(
    template="plotly_dark",
    paper_bgcolor="#111111",
    plot_bgcolor="#111111",
    font=dict(color="white"),
    title="Distribución de Propiedades",
    height=600,
    width=1300
)

fig.show()